simple_app/urls.py
from django.urls import path
from . import views

app_name = 'simple_app'

urlpatterns = [
    path("", views.home, name='home'),
    path("new-search/", views.search, name='search')
]

simple_project/urls.py
from django.contrib import admin
from django.urls import path, include
from simple_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('simple_app.urls'))
]

simple_app/models.py
from django.db import models

# Create your models here.
class Search(models.Model):
    search = models.CharField(max_length=500)
    created = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.search
    

    class Meta:
        verbose_name_plural = 'Searches'

simple_app/views.py
from django.shortcuts import render
from bs4 import BeautifulSoup
import requests

# Create your views here.
def home(request):
    return render(request, 'simple_app/base.html' )

def search(request):
    data_search = request.POST.get('search')
    data = {
        'data_search': data_search
    }
    return render(request, 'simple_app/new_search.html', data)

simple_app/templates/simple_app/base.html
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Simple Django App</title>
        <link rel="stylesheet" href="{% static "css/material-icons.css" %} ">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet">
    <link rel="stylesheet" href="{% static "css/materialize.min.css" %} ">
    <link rel="stylesheet" href="{% static "css/style.css"  %} ">
</head>

<body>
    <nav class="blue">
        <div class="container nav-wrapper">
            <a href="" class="brand-logo">Lovel</a>
            <ul id="nav-mobile" class="right">
                <li>
                    <a href="">Home</a>
                </li>
            </ul>
        </div>
    </nav>

<div class="container">
<section>
<h1 class="center flow-text">PLEASE ENTER WHAT YOU WANT TO SEARCH FOR IN LOVEL SEARCH</h1>
<div class="row">
    <div class="col s4">
        <div class="center">
            <i class="large material-icons" style="color: royalBlue">flash_on</i>
            <p>Fast Web Scarper</p>
            <p class="light center">Scrape away the right here with a beaautiful GUI</p> 
        </div>
    </div>
    <div class="col s4">
        <div class="center">
            <i class="large material-icons" style="color: royalBlue">camera</i>
            <p>Filter Searches</p>
            <p class="light center">I build more customize GUI to meet yor needs</p> 
        </div>
    </div>
    <div class="col s4">
        <div class="center">
            <i class="large material-icons" style="color: royalBlue">chrome_reader_mode</i>
            <p>Keep It Simple Frontend</p>
            <p class="light center">Easy to use/understand frontend design</p> 
        </div>
    </div>
</div>
</section>
<section class="center">
    <h2 class="light flow-text"> New Search <h2>

    <form action="{% url 'simple_app:search' %}" method ="POST">
        {% csrf_token %}
    <input type="text" name="search" placeholder="Enter search"/>
    <button type="submit" value="Search" class="btn blue glow z-index">Send<i class="material-icons right">send</i></button>
    </form >
</section>
{% block content %}
{% endblock content %}
</div>
  <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/materialize.min.js' %}"></script>
</body>

</html>

simple_app/templates/simple_app/new_search.html
{% extends 'simple_app/base.html' %} {% block content %}
<h2 class="center">{{ data_search | title}}</h2>
<div class="row">
    <div class="col m4">
        <div class="card">
            <div class="card-image">
                <a href="/"><img src="" alt=""></a>
            </div>
            <div class="card-content">
                <a href="/"></a>
            </div>
        </div>
    </div>
    <div class="col m4">
        <div class="card">
            <div class="card-image">
                <a href="/"><img src="" alt=""></a>
            </div>
            <div class="card-content">
                <a href="/"></a>
            </div>
        </div>
    </div>
    <div class="col m4">
        <div class="card">
            <div class="card-image">
                <a href="/"><img src="" alt=""></a>
            </div>
            <div class="card-content">
                <a href="/"></a>
            </div>
        </div>
    </div>
</div>
{% endblock content %}